package com.namnguyen.javatest4.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConfigAllPropertiesEquals(AppConfig expected, AppConfig actual) {
        assertAppConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertAppConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConfigAllUpdatablePropertiesEquals(AppConfig expected, AppConfig actual) {
        assertAppConfigUpdatableFieldsEquals(expected, actual);
        assertAppConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConfigAutoGeneratedPropertiesEquals(AppConfig expected, AppConfig actual) {
        assertThat(actual)
            .as("Verify AppConfig auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConfigUpdatableFieldsEquals(AppConfig expected, AppConfig actual) {
        assertThat(actual)
            .as("Verify AppConfig relevant properties")
            .satisfies(a -> assertThat(a.getKey()).as("check key").isEqualTo(expected.getKey()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConfigUpdatableRelationshipsEquals(AppConfig expected, AppConfig actual) {
        // empty method
    }
}
